## Lecture 7: Meiosis-3
Lesson outline
F. How do mitosis and meiosis differ? 
1. During mitosis and cell division, a body cell and its nucleus divide once and produce two 
identical cells. 
2. During meiosis, a reproductive cell and its nucleus divide twice and produce four cells––two 
pairs of identical haploid cells. 
G. Advantages of Sexual Reproduction 
1. Sexual reproduction produces offspring that have a new combination of DNA. This results in 
genetic variation among individuals. 
2. Genetic variation gives individuals within a population slight differences that might be an 
advantage if the environment changes. 
3. Selective breeding has been used to develop desirable traits in plants and animals. 
H. Disadvantages of Sexual Reproduction 
1. One disadvantage of sexual reproduction is that organisms have to grow and develop until 
they are mature enough to produce sex cells. 
2. Another disadvantage is that searching for a mate takes time and energy and might expose 
individuals to predators, diseases, or harsh environmental conditions.
